defaults:
  - train_occrae_img_decoder

output_dir: /mnt/proj1/eu-25-92/occrae_output

training:   
  view_chunk_size: 6


dataset:
  train_dataset: "2000 @ WaymoSeqMultiView(ROOT='/scratch/project/eu-25-92/data/waymo_processed', \
      seq_pkl_name='seq_surround_temporal_sub5_stride9_all.pkl', \
      min_memory_num_views=5, frame_interval=1, max_memory_num_views=24, \
      num_views_per_timestep=5, min_views_per_timestep=1, \
      z_far=50, split='train', \
      resolution=[(518, 294), (518, 280), (518, 266), (518, 210), (518, 168)], \
      reverse_seq=True, distill_model_name='SAM3', base_model='da3') + \
      1000 @ VKittiSeqMultiView(VKITTI_PROCESSED_ROOT='/scratch/project/eu-25-92/data/vkitti_processed', \
      seq_pkl_name='seq_exact_len_sub5_stride9.pkl', \
      min_memory_num_views=5, frame_interval=1, max_memory_num_views=10, \
      z_far=50, split='train', \
      resolution=[(518, 294), (518, 280), (518, 266), (518, 210), (518, 168)], \
      reverse_seq=True, distill_model_name='SAM3', base_model='da3') + \
      2000 @ DDADSeqMultiView(DDAD_PREPROCESSED_ROOT='/scratch/project/eu-25-92/data/ddad_processed', \
      seq_pkl_name='seq_surround_temporal_sub5_stride9_all.pkl', \
      min_memory_num_views=6, frame_interval=1, max_memory_num_views=24, \
      num_views_per_timestep=6, min_views_per_timestep=1, \
      z_far=50, split='train', \
      resolution=[(518, 294), (518, 280), (518, 266), (518, 210), (518, 168)], \
      reverse_seq=True, distill_model_name='SAM3', base_model='da3') + \
      2000 @ PandasetSeqMultiView(PANDASET_PREPROCESSED_ROOT='/scratch/project/eu-25-92/data/pandaset_processed', \
      seq_pkl_name='seq_surround_temporal_sub5_stride9_all.pkl', \
      min_memory_num_views=6, frame_interval=1, max_memory_num_views=24, \
      num_views_per_timestep=6, min_views_per_timestep=1, \
      z_far=50, split='train', \
      resolution=[(518, 294), (518, 280), (518, 266), (518, 210), (518, 168)], \
      reverse_seq=True, distill_model_name='SAM3', base_model='da3') + \
      2000 @ OnceSeqMultiView(ONCE_PREPROCESSED_ROOT='/scratch/project/eu-25-92/data/once_processed', \
      seq_pkl_name='seq_surround_temporal_sub5_stride9_all.pkl', \
      min_memory_num_views=5, frame_interval=1, max_memory_num_views=24, \
      num_views_per_timestep=5, min_views_per_timestep=1, \
      z_far=50, split='train', \
      resolution=[(518, 294), (518, 280), (518, 266), (518, 210), (518, 168)], \
      reverse_seq=True, distill_model_name='SAM3', base_model='da3')"
  test_dataset: "206 @ KittiSeqMultiView(KITTI_PREPROCESSED_ROOT='/scratch/project/eu-25-92/data/kitti_processed', \
      seq_pkl_name='seq_exact_len_sub5_stride9.pkl', frame_interval=1, \
      min_memory_num_views=5, max_memory_num_views=5, reverse_seq=False, \
      z_far=50, split='val', \
      resolution=[(518, 168)], distill_model_name='SAM3', base_model='da3') + \
      206 @ Occ3dNuscenesSeqMultiView(NUSCENES_PREPROCESSED_ROOT='/scratch/project/eu-25-92/data/occ3d_nuscenes_processed', \
      seq_pkl_name='seq_surround_temporal_sub1_stride9_all.pkl', frame_interval=1, \
      min_memory_num_views=18, max_memory_num_views=18, num_views_per_timestep=6, \
      z_far=50, split='val', \
      resolution=[(518, 294)], distill_model_name='SAM3', base_model='da3')"