exp_name: "overfit_ctx2pred2"

dataset:
  preprocess_data_root: /gpfs/scratch/ehpc558/quan/occrae_data
  subsampling_rate: 5
  max_stride: 3
  frame_stride: 1
  cond_num: 2
  processed_roots: ["ddad_processed"]
  val_processed_roots: ["ddad_processed"]
  max_train_samples: 1
  max_val_samples: 1

model:
  vit_size: "xlarge"
  num_views: 4
  pred_mode: "x"
  loss_mode: "v"
  mu: -0.7
  sigma: 1.4
  occany_recon_ckpt: "checkpoints/occany_plus_recon_1B.pth"
  encode_layer: 18

training:
  lr: 1e-4
  weight_decay: 0.05
  optimizer: "adamw"
  use_ema: false
  dtype: "bfloat16"
  global_epoch: 0
  iter: 0
  warm_up: 0
  max_iter: 100000
  epoch: 100
  bsize: 1
  num_workers: 0
  grad_cum: 1
  grad_clip: 1.0
  seed: 0
  virtual_epoch: 200
  eval_num_items: 256
  eval_num_steps: 50
