defaults:
  - train_deltatok

dataset:
  # Mirror img_decoder_karolina.yaml: same dataset roots on the Karolina cluster.
  train_dataset: "2000 @ WaymoSeqMultiView(ROOT='/scratch/project/eu-25-92/data/waymo_processed', \
      seq_pkl_name='seq_surround_temporal_sub5_stride9_all.pkl', \
      num_timesteps=5, num_views_per_timestep=5, fixed_cams=[0], \
      z_far=50, split='train', distill_model_name='SAM3', \
      resolution=[(518, 294), (518, 280), (518, 266), (518, 210), (518, 168)]) + \
      1000 @ VKittiSeqMultiView(VKITTI_PROCESSED_ROOT='/scratch/project/eu-25-92/data/vkitti_processed', \
      seq_pkl_name='seq_exact_len_sub5_stride9.pkl', \
      num_timesteps=5, fixed_cams=[0], \
      z_far=50, split='train', distill_model_name='SAM3', \
      resolution=[(518, 294), (518, 280), (518, 266), (518, 210), (518, 168)]) + \
      2000 @ DDADSeqMultiView(DDAD_PREPROCESSED_ROOT='/scratch/project/eu-25-92/data/ddad_processed', \
      seq_pkl_name='seq_surround_temporal_sub5_stride9_all.pkl', \
      num_timesteps=5, num_views_per_timestep=6, fixed_cams=[0], \
      z_far=50, split='train', distill_model_name='SAM3', \
      resolution=[(518, 294), (518, 280), (518, 266), (518, 210), (518, 168)]) + \
      2000 @ PandasetSeqMultiView(PANDASET_PREPROCESSED_ROOT='/scratch/project/eu-25-92/data/pandaset_processed', \
      seq_pkl_name='seq_surround_temporal_sub5_stride9_all.pkl', \
      num_timesteps=5, num_views_per_timestep=6, fixed_cams=[0], \
      z_far=50, split='train', distill_model_name='SAM3', \
      resolution=[(518, 294), (518, 280), (518, 266), (518, 210), (518, 168)]) + \
      2000 @ OnceSeqMultiView(ONCE_PREPROCESSED_ROOT='/scratch/project/eu-25-92/data/once_processed', \
      seq_pkl_name='seq_surround_temporal_sub5_stride9_all.pkl', \
      num_timesteps=5, num_views_per_timestep=5, fixed_cams=[0], \
      z_far=50, split='train', distill_model_name='SAM3', \
      resolution=[(518, 294), (518, 280), (518, 266), (518, 210), (518, 168)])"
  test_dataset: "206 @ KittiSeqMultiView(KITTI_PREPROCESSED_ROOT='/scratch/project/eu-25-92/data/kitti_processed', \
      seq_pkl_name='seq_exact_len_sub5_stride9.pkl', \
      num_timesteps=5, fixed_cams=[0], \
      z_far=50, split='val', seed=42, distill_model_name='SAM3', \
      resolution=[(518, 168)]) + \
      206 @ Occ3dNuscenesSeqMultiView(NUSCENES_PREPROCESSED_ROOT='/scratch/project/eu-25-92/data/occ3d_nuscenes_processed', \
      seq_pkl_name='seq_surround_temporal_sub5_stride9_all.pkl', \
      num_timesteps=5, num_views_per_timestep=6, fixed_cams=[0,1], \
      z_far=50, split='val', seed=42, distill_model_name='SAM3', \
      resolution=[(518, 266)])"
